### ISSUE TITLE
Failures on tornado 4.x

### ISSUE THREAD

**Issue by jayvdb** [takluyver/jupyter_kernel_mgmt#16]
When I build this on openSUSE build system for Tumbleweed, I am getting lots of `TypeError: 'Future' object is not iterable` and `AttributeError: module 'tornado.util' has no attribute 'TimeoutError'` .  I'm guessing it is incompatibility with the tornado version, which is stuck on the v4.5 branch due to latter versions having incompatibilities with salt. c.f. https://build.opensuse.org/package/show/devel:languages:python/python-tornado

https://build.opensuse.org/package/show/home:jayvdb:jupyter/python-jupyter-kernel-mgmt

Unfortunately most of the other parts of openSUSE's jupyter packages are all completely untested, so I am on shaking ground (and that might take a while to fix).

However it seems that either this project should have a minimum version of tornado, or a minimum version of jupyter_core/ipykernel/etc which provides a minimum version of tornado, so something like that.

```
[   19s] ======================================================================
[   19s] ERROR: test_inspect (jupyter_kernel_mgmt.tests.test_client.TestKernelClient)
[   19s] ----------------------------------------------------------------------
[   19s] Traceback (most recent call last):
[   19s]   File "/home/abuild/rpmbuild/BUILD/jupyter_kernel_mgmt-0.4.0/jupyter_kernel_mgmt/client.py", line 299, in wait_for_ready
[   19s]     yield from gen.with_timeout(second, reply_fut)
[   19s] TypeError: 'Future' object is not iterable
[   19s]
[   19s] During handling of the above exception, another exception occurred:
[   19s]
[   19s] Traceback (most recent call last):
[   19s]   File "/home/abuild/rpmbuild/BUILD/jupyter_kernel_mgmt-0.4.0/jupyter_kernel_mgmt/tests/test_client.py", line 28, in setUp
[   19s]     self.km, self.kc = start_new_kernel(kernel_cmd=make_ipkernel_cmd())
[   19s]   File "/home/abuild/rpmbuild/BUILD/jupyter_kernel_mgmt-0.4.0/jupyter_kernel_mgmt/subproc/launcher.py", line 322, in start_new_kernel
[   19s]     kc.wait_for_ready(timeout=startup_timeout)
[   19s]   File "/home/abuild/rpmbuild/BUILD/jupyter_kernel_mgmt-0.4.0/jupyter_kernel_mgmt/client.py", line 403, in wait_for_ready
[   19s]     loop.run_sync(lambda: self.loop_client.wait_for_ready(), timeout=timeout)
[   19s]   File "/usr/lib64/python3.7/site-packages/tornado/ioloop.py", line 457, in run_sync
[   19s]     return future_cell[0].result()
[   19s]   File "/usr/lib64/python3.7/site-packages/tornado/concurrent.py", line 237, in result
[   19s]     raise_exc_info(self._exc_info)
[   19s]   File "<string>", line 4, in raise_exc_info
[   19s]   File "/usr/lib64/python3.7/site-packages/tornado/gen.py", line 307, in wrapper
[   19s]     yielded = next(result)
[   19s]   File "/home/abuild/rpmbuild/BUILD/jupyter_kernel_mgmt-0.4.0/jupyter_kernel_mgmt/client.py", line 300, in wait_for_ready
[   19s]     except tornado.util.TimeoutError:
[   19s] AttributeError: module 'tornado.util' has no attribute 'TimeoutError'
```

**Comment by jayvdb** [comment]
I've got ipykernel 5.1.2 package now tested, and it passes the tests.  https://build.opensuse.org/request/show/721906

It depends on tornado >= 4.2.

**Comment by takluyver** [comment]
It looks like `tornado.util.TimeoutError` was created in 5.0. I don't know what the minimum tornado version this code requires is, but it appears to be at least that.

**Comment by kevin-bates** [comment]
I agree we need to nail this down.  I would prefer we take a more high-water approach, minimally pinning versions that are relatively recent - especially since the primary consumer will (potentially) be jupyter_server.  

Although Notebook 6 requires tornado >= 5, I'm inclined to push for tornado >= 6 so that we have a consistent async framework.  Of course this would be ramifications on the minimal config for jupyter_server, but I think that's the right approach.

What do others think?

**Comment by kevin-bates** [comment]
FYI: https://github.com/takluyver/jupyter_kernel_mgmt/pull/21

**Comment by jayvdb** [comment]
Well, this is a dependency of the test-kernel, which is need to validate kernels which are supposed to be compatible with jupyter, which is not tornado 5 or 6.  If this has a higher version of tornado it is not possible to use the test kernel to test against the same versions supported by jupyter.

**Comment by kevin-bates** [comment]
I see.  I'm not familiar with this library's usage outside of Notebook.  Is this why (perhaps) tornado wasn't listed in the dependencies in the first place?  I.e., let the hosting application use whatever tornado it needs?  I'll have to defer to @takluyver on this since that would require working around the issue above in another manner.

Could you share what the "test-kernel" is?  Was this affiliated with jupyter_client as well?

Until then, I recommend we keep the changes in #21 (unless the build breaks warrant further changes).

**Comment by jayvdb** [comment]
See https://github.com/jupyter/jupyter_kernel_test/commit/14ac018d4a232d637bd1d0c22658fc4480e34aca for context.  Apologies for not adding that earlier.

**Comment by kevin-bates** [comment]
Thanks John - that was helpful.  This is @takluyver's call, but I would suggest the dependency on `jupyter_kernel_mgmt` be made in a release _x_ of `jupyter_kernel_test` and let `< x` be based on `jupyter_client` releases and use pre-_x_ releases on openSUSE.

I think we need to keep the changes in #21 for this library.

**Comment by jayvdb** [comment]
This has nothing to do with openSUSE.  Adjusted title accordingly.  jupyter_kernel_mgmt is not compatible with jupyter_core's minimum requirements.  That is the problem.

**Comment by kevin-bates** [comment]
I was hoping @takluyver would have chimed in by now - sorry for the frustration.  

> jupyter_kernel_mgmt is not compatible with jupyter_core's minimum requirements.

In looking into jupyter_core, I don't really see any meaningful requirements specified nor does it even use tornado, so I don't understand this statement.  Could you please clarify?  Did you mean `jupyter_client`?

Here are a few options that come to mind...

1. Develop _compatibility shims_ like you did for python-flower.  However, that's a slippery slope as there will undoubtedly be others (`gen.with_timeout()` following the mapping of the `TimeoutError` uses), and implies this would be long road fraught with maintenance nightmares attempting to implement backwards compatibility in areas we need to move forward on (in particular async support).

2. jupyter_kernel_test has multiple releases so update the distro to use 0.3.  As stated on its readme, jupyter_kernel_mgmt is experimental and, typically, so is any master branch (e.g., jupyter_kernel_test/master).  If distros need to pin to a specific version of tornado, then it seems they should pin to a specific version of jupyter_kernel_test?   I understand that this approach may not guarantee that new aspects of the protocol get tested (assuming the jupyter_kernel_test follows those kinds of changes), but I think those level of changes should be made to the _previously released version_ as well.

    Seems like taking the [this commit](https://github.com/jupyter/jupyter_kernel_test/commit/0564c979e5dca22a0ca6f330ae33d805a6718da1), along with 0.3, and creating a 0.4 (or better yet, 1.0) release based on jupyter_client might be worthwhile.  Then, bump the 'dev iteration' to `2.0.0.dev` and that's where jupyter_kernel_mgmt comes in.  Any new protocol changes would then need to be backported to the both releases, 1.x remains on jupyter_client (and tornado < 5), 2.x (and master) uses jupyter_kernel_mgmt (and tornado >= 5).  Distros sensitive to tornado >= 5 would also need to pin jupyter_kernel_test < 2 - just as they must currently do for things like notebook < 6 (as it now also requires tornado >= 5).

3. Incorporate jupyter_kernel_test directly into the applicable packages.  I.e., jupyter_kernel_mgmt comes with kernel test functionality.  We could leave jupyter_kernel_test back on jupyter_client and those using jupyter_kernel_mgmt would use its built-in test facility.

I understand these aren't ideal, but unless someone has other ideas, option 2 seems like the most expedient approach for both worlds.  This also strikes me more of an issue for jupyter_kernel_test than jupyter_kernel_mgmt.

**Comment by takluyver** [comment]
Using this landed in jupyter_kernel_test at a point when it looked like it would soon be landing across the Jupyter ecosystem. But I don't think any released version of jupyter_kernel_test uses it. So you're packaging master of that but an old version of tornado.

As far as I'm concerned, the only problem to fix is that the minimum version of tornado isn't specified, and @kevin-bates is working on that in #21.

If this package does get adopted across Jupyter, then that minimum version would also apply to other projects, unless they have a higher minimum requirement themselves. So I don't buy the reasoning that it needs to support old tornado because other Jupyter components currently do.

**Comment by kevin-bates** [comment]
Closing this issue since JKM has a hard requirement of tornado >= 5.  I would recommend an approach similar to [option 2](https://github.com/takluyver/jupyter_kernel_mgmt/issues/16#issuecomment-521323969) above.
