### ISSUE TITLE
Document jupyter_kernel_mgmt

### ISSUE THREAD

**Issue by echarles** [takluyver/jupyter_kernel_mgmt#25]
As discussed during jupyter_server meeting with @takluyver @Zsailer @kevin-bates we need to document this repo (at least an architecture diagram).

This is valid also for https://github.com/takluyver/jupyter_protocol which btw has already a docs folder with a basic content which is prolly outdated and with content that should be moved here (eg https://github.com/takluyver/jupyter_protocol/blob/master/docs/kernel_providers.rst).

Or we document both repos separately, or we document everything here. I believe it would be best to document each repos separately. Thoughts?

**Comment by kevin-bates** [comment]
I agree this should be documented and also lean toward separate sets of docs.  I'm sure we'll find the two cross-referencing each other.  

@takluyver and I discussed this briefly a while back.  I want to say we came to the same conclusion (separate doc sets), but am not 100% on that.

**Comment by kevin-bates** [comment]
@takluyver - Per my [comment on the jupyter_protocol doc issue](https://github.com/takluyver/jupyter_protocol/issues/3#issuecomment-546611035), we should try to complete the readthedocs.io integration soon.  Thank you.

**Comment by echarles** [comment]
Closing this, we have now a basic docs on https://jupyter-kernel-mgmt.readthedocs.io
